### ISSUE TITLE
Plugin requires unnecessarily recent weekly release of Jenkins

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/vk-notifier-plugin#1]
https://github.com/jenkinsci/vk-notifier-plugin/blob/5c1836a23bb730723b2d46f537385ec2750a15fb/build.gradle#L35

This (likely unnecessarily) limits who can use your plugin. See https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

**Comment by Spliterash** [comment]
Done
